### PR TITLE
Speed is not displayed (dump1090-mutability)

### PR DESCRIPTION
**Pull request by skaringa**
I run tar1090 with dump1090-mutability and I have to apply this patch to show the speed in the airplane labels and the table on the right. This is related to the fix you've done for #111, but in my opinion this fix was incomplete.

### CODE REVIEW

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/tar1090/commit/aad646dd430fe530d889f2588c58d3a071147d40

should be fixed. this PR wasn't the right thing to do.

**Comment by skaringa** [comment]
> should be fixed. this PR wasn't the right thing to do.
I don't understand. It is definitely not fixed without my patch. And why is a PR not the right thing to provide patches? What would be the right thing?

**Comment by wiedehopf** [comment]
I pushed a commit which is linked.

**Comment by wiedehopf** [comment]
Feel free to let me know if my commit didn't fix the issue.

**Pull request closed without merging**
