### PR TITLE
Update install.sh for rbfeeder

### PR DESCRIPTION
**Pull request by vatprcyq**
tar1090 for rbfeeder aircraft.json location update

### CODE REVIEW

**Comment by wiedehopf** [comment]
Does their default setup open port 30005 for others to use the data?

**Comment by vatprcyq** [comment]
> Does their default setup open port 30005 for others to use the data?
Port number is different
Basestation at port 32459 and Beast port 32457
But access restricted at localhost
Can use socat or nc to forward port

**Comment by wiedehopf** [comment]
Why would the not open the default ports of the project they forked?
localhost restriction is fine, not opening the default ports is ridiculous.

I won't support them until that is changed.

**Comment by wiedehopf** [comment]
If you want to use tar1090, plese use either dump1090-fa or readsb as a decoder.
https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb

readsb is recommended because it's what i'm developing.

**Comment by vatprcyq** [comment]
> If you want to use tar1090, plese use either dump1090-fa or readsb as a decoder. https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb
> 
> readsb is recommended because it's what i'm developing.

OK change to readsb now,use network mode for rbfeeder

**Comment by vatprcyq** [comment]
> If you want to use tar1090, plese use either dump1090-fa or readsb as a decoder. https://github.com/wiedehopf/adsb-scripts/wiki/Automatic-installation-for-readsb
> 
> readsb is recommended because it's what i'm developing.

readsb can decode MCP select ALT ,rbfeeder can't do this now

**Pull request closed without merging**
