### PR TITLE
North Atlantic Tracks geojson & UI

### PR DESCRIPTION
**Pull request by kevdel**
NAT East & West geojson files and additions to the UI for selection

### CODE REVIEW

**Comment by wiedehopf** [comment]
I'll need to somehow make submenus in the layer selector.
Which has its own drawbacks :/

Might be a day or 2 but i'll get to it.

**Comment by kevdel** [comment]
Might need to hold off on this pull request. The tracks change location daily. 

More reading required..

**Comment by wiedehopf** [comment]
They do indeed, i'm aware but didn't even think of it.

**Comment by wiedehopf** [comment]
How about you open a new one once you have figured it out :)

**Comment by kevdel** [comment]
10/4

**Comment by kevdel** [comment]
I mocked up a test page to pull the latest tracks from https://ganderoceanic.com/ and map them on a sample map.
https://github.com/kevdel/tar1090/commit/3cd35f1ef079dc94ef73579a7b45f4c7d4abbc2e

Couple of things to work out if you think this approach would work

1. What to do when there are no tracks (no data, bad data, actually no tracks (low aircraft traffic & space based navigation))
2. Track Naming Convention & displayed text on map
3. Colors

**Pull request closed without merging**
