### PR TITLE
add altimeter pressure correction

### PR DESCRIPTION
**Pull request by justin4046**

### CODE REVIEW

**Comment by wiedehopf** [comment]
I'm getting the formula a bit more precise, not that it matters.
Just wanted to also provide a reference as to which formula was used.

Your formula was off by 2ft at 10k ft and 6 ft at 40k ft.
Which is obviously irrelevant but wanted to check the code vs this reference: https://www.weather.gov/media/epz/wxcalc/pressureAltitude.pdf

**Comment by wiedehopf** [comment]
See recent commits if you're curious about the changes i made to this PR.

**Comment by justin4046** [comment]
Thanks. This was my source for station pressure. https://www.weather.gov/media/epz/wxcalc/stationPressure.pdf
Probably an unnecessary inhg conversion

**Comment by wiedehopf** [comment]
Think you took the inverse of the exponent from wikipedia.
And that exponent is a bit off on wikipedia for some reason.
And getting rid of conversions helps of course :)

**Pull request merged**
