### PR TITLE
Using flag-icons library

### PR DESCRIPTION
**Pull request by makrsmark**
the original flags come from a website that is not maintained.

* new flags are pulled from https://github.com/lipis/flag-icons
* renamed min.js to include the version
* added css to keep flags from hiding

fixes wiedehopf/tar1090#263

### CODE REVIEW

**Comment by wiedehopf** [comment]
So ... i've finally looked at this.
I've massaged it to where i like it except for one somewhat important detail.
Aspect ratio of the flags.
4x3 just doesn't look as nice as the 5x3 the previous flags are using.
3x2 would also be fine, but 4x3 is just too square.


Thus i might just keep it in the flags branch and not pursue further, sorry!
Might just be easier to deal with the individual flag pngs and update those, we will see.
Possibly i'll use it at some point.

**Comment by makrsmark** [comment]
@wiedehopf would it be worth looking at https://www.npmjs.com/package/country-flag-icons instead?

**Comment by wiedehopf** [comment]
It is indeed, i can fiddle around myself thank you.

https://gitlab.com/catamphetamine/country-flag-icons/-/blob/master/flags/3x2/flags.css?ref_type=heads

This doesn't seem to be updated otherwise i'd very much like a single file solution.

**Comment by wiedehopf** [comment]
There seem to be 2 3x2 folders, so it's a bit confusing which is the updated one?

Seems they are both updated and the build propagates from one to the other.

**Comment by wiedehopf** [comment]
https://github.com/wiedehopf/tar1090/commit/ee4b382c92d72b3d5d7860ee544de6a25ed08186

squashed it all down to 1 commit as i don't like to keep any extra data / files in the git history.
added myself as co-author.

The flags folder has a README.md that links back to the repo the flags are taken from.
Also added the MIT license in there.

Does that seem fine like that to you?
Thank you for adding all the country codes to icao.js btw, just noticed that that was necessary :)

**Comment by makrsmark** [comment]
works for me!

**Pull request merged**
