### PR TITLE
Linting & Addition of Github Actions

### PR DESCRIPTION
**Pull request by mikenye**
- Linted the `install.sh` & `uninstall.sh` scripts.
- Added Github actions to:
  - Perform linting on push/pull_request to master branch
  - Test running `install.sh` and `uninstall.sh`

I'd suggest a squash merge if you're planning to merge this, due to my many commits. :)

### CODE REVIEW

**Comment by mikenye** [comment]
Note, commit bbe6a8c contains the change from pull request #58, which I see you have just closed and changed....

**Comment by mikenye** [comment]
Fixed tar1090.sh - now matches master branch.

**Comment by wiedehopf** [comment]
how should i review this o_O

**Comment by wiedehopf** [comment]
merged manually.

**Pull request closed without merging**
